# Generated by Django 3.2.3 on 2021-05-30 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20210530_0252'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='')),
                ('like', models.BooleanField(default=False)),
            ],
        ),
    ]
