# Generated by Django 3.2.3 on 2021-05-30 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_memberpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberpost',
            name='image',
        ),
    ]
