# Generated by Django 3.2.3 on 2021-05-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_memberpost_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='books/')),
                ('link', models.CharField(max_length=200)),
                ('link2', models.CharField(max_length=200, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
