# Generated by Django 3.2.3 on 2021-05-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_book2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book2',
            name='link2',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
