# Generated by Django 3.2.3 on 2021-05-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_book2_link2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book2',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='link',
            new_name='link1',
        ),
        migrations.AddField(
            model_name='book',
            name='link2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='link3',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
