# Generated by Django 3.2.3 on 2021-06-02 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0009_auto_20210530_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='article',
            name='like',
        ),
        migrations.RemoveField(
            model_name='article',
            name='like_count',
        ),
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
