# Generated by Django 3.2.3 on 2021-06-01 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_articlelike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='article',
            name='like',
        ),
        migrations.RemoveField(
            model_name='article',
            name='like_count',
        ),
    ]
