# Generated by Django 3.2.3 on 2021-06-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20210602_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlelike',
            name='like',
            field=models.BooleanField(default=True),
        ),
    ]
