# Generated by Django 3.2.3 on 2021-06-01 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_articlelike_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlelike',
            name='like',
        ),
    ]
