# Generated by Django 3.2.4 on 2021-06-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20210602_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.FileField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='filesadmin',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='nasanew',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='pdfupload',
            field=models.FileField(upload_to='media'),
        ),
    ]
